FROM node:20.19.5-alpine3.21 AS build
WORKDIR /opt/server
COPY *.json *.js .
RUN npm install

FROM node:20.19.5-alpine3.21
WORKDIR /opt/server
EXPOSE 8080
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && \
    chown -R roboshop:roboshop /opt/server
LABEL com.project="roboshop" \
      component="catalogue"
ENV MONGO="true" \
    MONGO_URL="mongodb://mongodb:27017/catalogue" 
COPY --from=build --chown=roboshop:roboshop /opt/server /opt/server
USER roboshop
ENTRYPOINT ["node","server.js"]

# FROM node:20.19.5-alpine3.21 AS build
# WORKDIR /opt/server
# EXPOSE 8080
# COPY *.json .
# COPY *.js .
# RUN npm install
# ENV MONGO="true" \
#     MONGO_URL="mongodb://mongodb:27017/catalogue"
# CMD ["node","server.js"]
